theme: jekyll-theme-cayman
title: [Pili Guerra]
description: [Welcome to my website]
url: https://piliguerra.com
author: 
  picture: /img/pili.png
  twitter: mpguerra
plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-avatar
   - jekyll-include-cache
