title: Jagged Little Pili
description: A little bit of everything
url: "https://piliguerra.com"
baseurl: ""
remote_theme: willianjusten/will-jekyll-template

# User settings
username: Jagged Little Pili
user_description: Technologist, troubleshooter, maker
user_title: Pili Guerra
email: pili@piliguerra.com
twitter_username: mpguerra
github_username:  mpguerra
instagram_username: mpguerra
author: Pili Guerra
user_pgp_fingerprint: "3E7F A89E 2459 B6CC A62F  56B8 C6CB 772E F096 9C45"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
clippings: all
comments: all
endings: []
profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Photos
    url: https://photos.piliguerra.com
    external: true
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

plugins:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
- jekyll-avatar
- jekyll-include-cache

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
